kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - kms:
        name : barbican
        endpoint: unix:///tmp/socketfile.sock
        cachesize: 20
    - identity: {}
